name: Publish Mod

# Run when a new release is... released
on: 
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Use checkout to publish the files in your repo
      - uses: actions/checkout@v3
      - uses: GreenTF/upload-thunderstore-package@v4.2
        with:
          token: ${{ secrets.token }}
          community: lethal-company
          namespace: Parmi_nous # the thunderstore 'team' to publish under
          name: ${{ github.repository }} # Use the repo name as the package name
          description: Lethal Company modpack for Parmi Nous &amp; USCC discord servers
          version: ${{ github.ref_name }} # Use the tag as the package version
          categories: | # <-- notice this pipe character
            modpacks